apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage-dns
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: sachinjiyer@gmail.com
    privateKeySecretRef:
      name: letsencrypt-stage-dns
    solvers:
      - selector:
          dnsZones:
            - "sachiniyer.com"
        dns01:
          route53:
            region: us-east-1
            accessKeyIDSecretRef:
              name: prod-route53-credentials-secret
              key: access-key-id
            secretAccessKeySecretRef:
              name: prod-route53-credentials-secret
              key: secret-access-key
---
apiVersion: v1
kind: Secret
metadata:
  name: prod-route53-credentials-secret
  namespace: cert-manager
type: Opaque
data:
  access-key-id:
  secret-access-key:
