---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: school-demo-ingress
spec:
  tls:
  - secretName: school-demo-cert
  rules:
  - host: school-demo.sachiniyer.com
    http:
      paths:
       - path: /
         pathType: Prefix
         backend:
           service:
             name: school-demo-service
             port:
               number: 3000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: school-demo-cert
  namespace: school-demo
spec:
  commonName: school-demo.sachiniyer.com
  secretName: school-demo-cert
  dnsNames:
    - school-demo.sachiniyer.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: v1
kind: Service
metadata:
  name: school-demo-service
  labels:
    run: school-demo
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app:  school-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-demo-deployment
spec:
  selector:
    matchLabels:
      app: school-demo
  template:
    metadata:
      labels:
        app: school-demo
    spec:
      containers:
      - name: school-demo
        image: sachiyer/school-demo
        env:
          - name: DATA
            value: /app/data
        ports:
        - containerPort: 3000
