---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-wasm
spec:
  selector:
    matchLabels:
      app: pong-wasm
  template:
    metadata:
      labels:
        app: pong-wasm
    spec:
      containers:
        - name: pong-wasm
          image: sachiyer/pong-wasm
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pong-wasm
spec:
  selector:
    app: pong-wasm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pong-wasm-cert
  namespace: pong-wasm
spec:
  commonName: pong.sachiniyer.com
  secretName: pong-wasm-cert
  dnsNames:
    - pong.sachiniyer.com
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect
  namespace: pong-wasm
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: pong-wasm-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: pong-wasm-redirect@kubernetescrd
spec:
  tls:
    - secretName: pong-wasm-cert
  rules:
    - host: pong.sachiniyer.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pong-wasm
                port:
                  number: 80
