---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: privatebin-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: privatebin-redirect@kubernetescrd
spec:
  tls:
  - secretName: privatebin-cert
  rules:
  - host: bin.sachiniyer.com
    http:
      paths:
       - path: /
         pathType: Prefix
         backend:
           service:
             name: privatebin
             port:
               number: 8080
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: privatebin-cert
  namespace: privatebin
spec:
  commonName: bin.sachiniyer.com
  secretName: privatebin-cert
  dnsNames:
    - bin.sachiniyer.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect
  namespace: privatebin
spec:
  redirectScheme:
    scheme: https
    permanent: true
