---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: bitwarden-ingress
spec:
  tls:
    - secretName: bitwarden-cert
  rules:
    - host: pass.sachiniyer.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bitwarden-bitwarden-k8s
                port:
                  number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-cert
  namespace: bitwarden
spec:
  commonName: pass.sachiniyer.com
  secretName: bitwarden-cert
  dnsNames:
    - pass.sachiniyer.com
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
