# Default values for bitwarden-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: vaultwarden/server
  tag: latest
  pullPolicy: IfNotPresent
  # imagePullSecrets for accessing private registries
  # pullSecrets: regcred

env:
  SIGNUPS_ALLOWED: false
  INVITATIONS_ALLOWED: true
  DOMAIN: https://pass.sachiniyer.com
  ADMIN_TOKEN:
  # YUBICO_CLIENT_ID
  # YUBICO_SECRET_KEY
  # DATA_FOLDER
  # DATABASE_URL
  # ATTACHMENTS_FOLDER
  # ICON_CACHE_FOLDER
  # ROCKET_LIMITS
  # ROCKET_WORKERS
  # SMTP_HOST
  # SMTP_FROM
  # SMTP_PORT
  # SMTP_SSL
  # SMTP_EXPLICIT_TLS
  # SMTP_USERNAME
  # SMTP_PASSWORD
  SHOW_PASSWORD_HINT: true
  # WEB_VAULT_ENABLED

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  loadBalancerIP:

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - bitwarden.example
  tls:
    - secretName: bitwarden-tls
      hosts:
        - bitwarden.example

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

deploymentAnnotations: {}

## Persist data to a persitent volume
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 800Mi
  storageClass: rook-ceph-block
  #existingClaim: "bitwarden-pvc"
