---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: filebrowser-ingress
spec:
  tls:
    - secretName: filebrowser-cert
  rules:
    - host: share.sachiniyer.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: filebrowser
                port:
                  number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: filebrowser-cert
  namespace: filebrowser
spec:
  commonName: share.sachiniyer.com
  secretName: filebrowser-cert
  dnsNames:
    - share.sachiniyer.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
