---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: filebrowser-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: filebrowser-redirect@kubernetescrd
spec:
  tls:
    - secretName: filebrowser-cert
  rules:
    - host: share.sachiniyer.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: filebrowser
                port:
                  number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: filebrowser-cert
  namespace: filebrowser
spec:
  commonName: share.sachiniyer.com
  secretName: filebrowser-cert
  dnsNames:
    - share.sachiniyer.com
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect
  namespace: filebrowser
spec:
  redirectScheme:
    scheme: https
    permanent: true
