---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kutt-cert
  namespace: kutt
spec:
  commonName: s.sachiniyer.com
  secretName: kutt-cert
  dnsNames:
    - s.sachiniyer.com
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect
  namespace: kutt
spec:
  redirectScheme:
    scheme: https
    permanent: true
