apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian
  namespace: debian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian
  template:
    metadata:
      labels:
        app: debian
    spec:
      containers:
        - name: debian
          image: debian:latest
          command: ["sleep", "infinity"]
