apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s-app: resume-website
  name: resume-website
  namespace: website
data:
  nginx-docs.conf: |
    server {
        listen       80;
        server_name localhost;

        location / {
            root   /usr/share/nginx/html/resume.git;
            try_files /resume.pdf =404;
        }

        error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html/resume.git;
        }
    }
