apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-cert
  namespace: blog
spec:
  commonName: blog.sachiniyer.com
  secretName: blog-cert
  dnsNames:
    - blog.sachiniyer.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect
  namespace: blog
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: blog-ingress
  namespace: blog
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: blog-redirect@kubernetescrd
spec:
  tls:
  - secretName: blog-cert
  rules:
  - host: blog.sachiniyer.com
    http:
      paths:
      - path: /sync
        pathType: Prefix
        backend:
          service:
            name: hugo-service
            port:
              number: 90
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hugo-service
            port:
              number: 80
