---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: matomo-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: matomo-redirect@kubernetescrd
spec:
  tls:
  - secretName: matomo-cert
  rules:
  - host: track.sachiniyer.com
    http:
      paths:
       - path: /
         pathType: Prefix
         backend:
           service:
             name: matomo
             port:
               number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: matomo-cert
  namespace: matomo
spec:
  commonName: track.sachiniyer.com
  secretName: matomo-cert
  dnsNames:
    - track.sachiniyer.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect
  namespace: matomo
spec:
  redirectScheme:
    scheme: https
    permanent: true
