apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysite-ingress
  namespace: website
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: website-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: sachiniyer.com
    http:
      paths:
      - path: /sync
        pathType: Prefix
        backend:
          service:
            name: mysite-service
            port:
              number: 90
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mysite-service
            port:
              number: 80
  tls:
  - secretName: website-cert
