apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysite-ingress
  namespace: website
spec:
  ingressClassName: traefik
  rules:
  - host: sachiniyer.com
    http:
      paths:
      - backend:
          service:
            name: mysite-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - secretName: website-cert
