apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: secure-test-sachiniyer-cert
spec:
  commonName: secure-test.sachiniyer.com
  secretName: secure-test-sachiniyer-cert
  dnsNames:
    - secure-test.sachiniyer.com
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
