# docker run -d -it -v /path/on/host:/data -e EULA=TRUE -p 25565:25565 --name mc itzg/minecraft-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data-pvc
      containers:
      - name: minecraft-server
        image: itzg/minecraft-server:latest
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1.5Gi
        env:
          - name:  EULA
            value: 'TRUE'
            value: 'Sachin Minecraft Server'
          - name: ALLOW_FLIGHT
            value: 'FALSE'
          - name: OPS
            value: 'nichas1,ilyxandra'
          - name: ALLOW_NETHER
            value: 'true'
          - name: ENABLE_COMMAND_BLOCK
            value: 'true'
          - name: GENERATE_STRUCTURES
            value: 'true'
          - name: SNOOPER_ENABLED
            value: 'false'
          - name: SPAWN_ANIMALS
            value: 'true'
          - name: SPAWN_MONSTERS
            value: 'true'
          - name: SPAWN_NPCS
            value: 'true'
          - name: MODE
            value: 'survival'
          - name: PVP
            value: 'false'
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
          - name: minecraft-data
            mountPath:  /data
        readinessProbe:
          exec:
            command:
            - mcstatus
            - 127.0.0.1
            - ping
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          exec:
            command:
            - mcstatus
            - 127.0.0.1
            - ping
          initialDelaySeconds: 30
          periodSeconds: 30
