apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  type: LoadBalancer
  selector:
    app: minecraft-server
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
