kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-data-pvc
  namespace: minecraft
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
