apiVersion: apps/v1
kind: Deployment
metadata:
  name: digits-front
spec:
  selector:
    matchLabels:
      app: digits-front
  template:
    metadata:
      labels:
        app: digits-front
    spec:
      containers:
        - name: digits-front
          image: sachiyer/mnist-wasm-site:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: digits-front
spec:
  selector:
    app: digits-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: digits-front-cert
  namespace: digits
spec:
  commonName: digits.sachiniyer.com
  secretName: digits-front-cert
  dnsNames:
    - digits.sachiniyer.com
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect
  namespace: digits
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: digits-front-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: digits-redirect@kubernetescrd
spec:
  tls:
    - secretName: digits-front-cert
  rules:
    - host: digits.sachiniyer.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: digits-front
                port:
                  number: 80
