---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meal-finder-front
spec:
  selector:
    matchLabels:
      app: meal-finder-front
  template:
    metadata:
      labels:
        app: meal-finder-front
    spec:
      containers:
        - name: meal-finder-front
          image: sachiyer/meal-finder-front
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              value: https://meal-finder-api.sachiniyer.com
            - name: API_URL
              value: https://meal-finder-api.sachiniyer.com
---
apiVersion: v1
kind: Service
metadata:
  name: meal-finder-front
spec:
  selector:
    app: meal-finder-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: meals-front-cert
  namespace: meal-finder
spec:
  commonName: meals.sachiniyer.com
  secretName: meals-front-cert
  dnsNames:
    - meals.sachiniyer.com
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect
  namespace: meal-finder
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: meal-finder-front-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: meal-finder-redirect@kubernetescrd
spec:
  tls:
    - secretName: meals-front-cert
  rules:
    - host: meals.sachiniyer.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meal-finder-front
                port:
                  number: 80
